name: Run All Tests
on:
  push:
    branches:
      - master
      - main
      - develop
      - features/*
      - bugfix/*
  pull_request:
    branches: 
      - master
      - main
      - develop
      - features/*
      - bugfix/*
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run Jest
        run: npm test
      - name: Run Playwright tests
        run: npm run test:e2e
